spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tutorial-rds.c5ngdfgsyitn.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: wldnd506

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database : mysql

  logging:
    level:
      org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error

cloud:
  aws:
    credentials:
      access-key: AKIA5VPD35GFMK4J5S6Z
      secret-key: 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
    region:
      static: ap-northeast-2 # AWS SQS의 리전정보
    stack:
      auto: false
    sqs:
      queue:
        name: MyQueue   # AWS에서 생성한 Queue 이름
        url: https://sqs.ap-northeast-2.amazonaws.com/939465107850/MyQueue # 생성한 SQS 큐 url

